network:
  version: 2
  renderer: networkd
  wifis:
    wlp8s0:
      dhcp4: no
      dhcp6: no
      optional: true
      addresses: [192.168.1.22/24]
      gateway4: 192.168.1.254
      nameserwers:
        addresses: [62.233.233.233, 8.8.8.8]
      access-points:
        "My wifi name":
          password: "My wifi password"
